// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapicall.Data;

#nullable disable

namespace webapicall.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Scholarship", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("academicstanding")
                        .HasColumnType("TEXT");

                    b.Property<string>("activities")
                        .HasColumnType("TEXT");

                    b.Property<string>("amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("citizenship")
                        .HasColumnType("TEXT");

                    b.Property<string>("contactinfoaddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("contactinfoemail")
                        .HasColumnType("TEXT");

                    b.Property<string>("contactinfoname")
                        .HasColumnType("TEXT");

                    b.Property<string>("contactinfophone")
                        .HasColumnType("TEXT");

                    b.Property<string>("courseload")
                        .HasColumnType("TEXT");

                    b.Property<string>("deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("fieldofstudy")
                        .HasColumnType("TEXT");

                    b.Property<string>("financialneed")
                        .HasColumnType("TEXT");

                    b.Property<string>("gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("heritage")
                        .HasColumnType("TEXT");

                    b.Property<string>("levelofstudy")
                        .HasColumnType("TEXT");

                    b.Property<string>("link")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("regionofresidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("regionofstudy")
                        .HasColumnType("TEXT");

                    b.Property<string>("schoolofstudy")
                        .HasColumnType("TEXT");

                    b.Property<string>("schoolsattended")
                        .HasColumnType("TEXT");

                    b.Property<string>("yearofstudy")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Scholarships");

                    b.HasData(
                        new
                        {
                            id = 1,
                            academicstanding = "80",
                            activities = "n/s",
                            amount = "$500",
                            citizenship = "Any",
                            contactinfoaddress = "4401 University Drive West, Lethbridge, AB, Canada.  T1K 3M4",
                            contactinfoemail = "N/A",
                            contactinfoname = "University of Lethbridge",
                            contactinfophone = "403-329-2741",
                            courseload = "Full-time",
                            deadline = "March 15, 2024",
                            fieldofstudy = "Drama and Dramatics/Theatre Arts, General, Education, General, Fine/Studio Arts, General, Music, General",
                            financialneed = "No",
                            gender = "N/A",
                            heritage = "N/A",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/4132/Robert-M.-Cook-Scholarship-in-Fine-Arts",
                            name = "Robert M. Cook Scholarship in Fine Arts",
                            notes = "New high school students entering a Bachelor of Fine Arts, Bachelor of Music, Bachelor of Fine Arts/Bachelor of Education, or Bachelor of Music/Bachelor of Education degree at the University of Lethbridge. Students must demonstrate academic achievement (minimum 80% admission average), and have achieved a minimum of 80% in at least one Fine Arts discipline from high school. Nominated by the Faculty of Fine Arts. Payable upon confirmation of full-time enrolment in classes at the University of Lethbridge in the Fall and Spring terms immediately following the granting of the award.",
                            regionofresidence = "n/s",
                            regionofstudy = "Alberta",
                            schoolofstudy = "University of Lethbridge",
                            schoolsattended = "Any School",
                            yearofstudy = "Entering first year"
                        },
                        new
                        {
                            id = 3,
                            academicstanding = "N/A",
                            activities = "n/s",
                            amount = "$20,000",
                            citizenship = "Canada",
                            contactinfoaddress = "The Centre, 1st Floor, Ira Needles Hall, University of Waterloo, Waterloo, ON, Canada.  N2L 3G1",
                            contactinfoemail = "safainfo@uwaterloo.ca",
                            contactinfoname = "Jessica Bruni",
                            contactinfophone = "(519) 888-4567 ext 46603",
                            courseload = "Full-time",
                            deadline = "April 15, 2024",
                            fieldofstudy = "Computer Engineering, General, Computer Software Engineering, Management Science, General, Mechatronics, Robotics, and Automation Engineering, Systems Engineering",
                            financialneed = "No",
                            gender = "Any",
                            heritage = "Black,Indigenous",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/75174/Vitaly-Pecherskiy-Entrance-Award-for-Black-and-Indigenous-Students",
                            name = "Vitaly Pecherskiy Entrance Award for Black and Indigenous Students",
                            notes = "One award valued at $20,000, or two awards valued at $10,000 each, will be provided to Black and/or Indigenous undergraduate students entering Year One of Computer, Management, Mechatronics, Software or Systems Design Engineering. For the purpose of this scholarship, an Indigenous person is a person who self identifies as First Nations (Status/Non-Status), M�tis and/or Inuit. Candidates must be a Canadian citizen, permanent resident, or a protected person in Canada. Selection will be based on a combination of academic achievement, the Admission Information Form (AIF), the online video interview, as well as an application statement wherein students are asked to describe the impact this award will have on their pursuit of postsecondary studies. Interested students should submit an online application by April 15.",
                            regionofresidence = "n/s",
                            regionofstudy = "Ontario",
                            schoolofstudy = "University of Waterloo",
                            schoolsattended = "Any School",
                            yearofstudy = "Entering first year, Entering or in first year"
                        },
                        new
                        {
                            id = 4,
                            academicstanding = "N/A",
                            activities = "n/s",
                            amount = "$1,650",
                            citizenship = "Any",
                            contactinfoaddress = "The Centre, 1st Floor, Ira Needles Hall, University of Waterloo, Waterloo, ON, Canada.  N2L 3G1",
                            contactinfoemail = "safainfo@uwaterloo.ca",
                            contactinfoname = "Jessica Bruni",
                            contactinfophone = "(519) 888-4567 ext 46603",
                            courseload = "Full-time",
                            deadline = "April 15, 2024",
                            fieldofstudy = "Architecture (BArch, BA/BS, MArch, MA/MS, PhD), Chemical Engineering, Civil Engineering, General, Computer Engineering, General, Computer Software Engineering, Electrical, Electronics and Communications Engineering�more, Engineering, General, Environmental/Environmental Health Engineering, Geological/Geophysical Engineering, Management Science, General, Mechanical Engineering, Nanotechnology, Systems Engineering�less",
                            financialneed = "No",
                            gender = "Any",
                            heritage = "Black,Indigenous",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/75072/Aziz-Shallwani-Memorial-Award-for-Black-and-Indigenous-Students",
                            name = "Aziz Shallwani Memorial Award for Black and Indigenous Students",
                            notes = "An award, valued at up to $1,650, will be provided annually to a Black or Indigenous undergraduate student entering Year One of any program in the Faculty of Engineering. For the purpose of this scholarship, an Indigenous person is a person who self identifies as First Nations (Status/Non-Status), M�tis and/or Inuit. Selection will be based on a combination of academic achievement, the Admission Information Form (AIF), the online video interview, as well as an application statement wherein students are asked to describe the impact this award will have on their pursuit of post-secondary studies.",
                            regionofresidence = "n/s",
                            regionofstudy = "Ontario",
                            schoolofstudy = "University of Waterloo",
                            schoolsattended = "Any School",
                            yearofstudy = "Entering first year, Entering or in first year"
                        },
                        new
                        {
                            id = 6,
                            academicstanding = "N/A",
                            activities = "Exchange Program",
                            amount = "N/A",
                            citizenship = "Any",
                            contactinfoaddress = "Faculty of Health Sciences, University of Ottawa, 539-540 King Edward, Ottawa, ON, Canada.  K1N 6N5",
                            contactinfoemail = "fssrecherche@uottawa.ca",
                            contactinfoname = "Celine Marie",
                            contactinfophone = "613-562-5800 ext 1398",
                            courseload = "Full-time or Part-time",
                            deadline = "March 31, 2024",
                            fieldofstudy = "Accounting, Business Administration and Management, General, Business Administration, Management and Operations, Other, Business/Commerce, General, Entrepreneurship/Entrepreneurial Studies, Finance, General�more, Health Services Administration, Health/Health Care Administration/Management, Human Resources Management/Personnel Administration, General, International Business/Trade/Commerce, Law (LL.B, J.D., B.C.L.), Management Information Systems, General, Management Science, General, Marketing/Marketing Management, General�less",
                            financialneed = "Yes",
                            gender = "Any",
                            heritage = "N/A",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/57154/Chrysler-Canada-International-Exchange-Fund",
                            name = "Chrysler Canada International Exchange Fund",
                            notes = "To help offset travel expenses for students of the Telfer School of Management participating in international exchange programs. The applicant must: be registered in a program at the Telfer School of Management of the University of Ottawa; participate in international exchange programs; and demonstrate financial need, as determined by the Financial Aid and Awards Service.",
                            regionofresidence = "n/s",
                            regionofstudy = "Ontario",
                            schoolofstudy = "Telfer School of Management, University of Ottawa/Universit� d'Ottawa",
                            schoolsattended = "Any School",
                            yearofstudy = "Entering or in first year, Entering or in second year, Entering or in third year, Entering or in fourth year"
                        },
                        new
                        {
                            id = 7,
                            academicstanding = "92",
                            activities = "Extracurricular Activities",
                            amount = "$11,500",
                            citizenship = "Canada",
                            contactinfoaddress = "Desmarais Building, 55 Laurier Avenue East, Room 3156	, Ottawa, ON, Canada.  K1N 6N5",
                            contactinfoemail = "loansandawards@uOttawa.ca",
                            contactinfoname = "Financial Aid and Awards",
                            contactinfophone = "613-562-5734",
                            courseload = "Full-time",
                            deadline = "March 15, 2024",
                            fieldofstudy = "Biochemistry, Biology/Biological Sciences, General, Biomedical Sciences, General, Chemistry, General, Economics, General, Environmental Science�more, Financial Mathematics, Geography, Geology/Earth Science, General, Mathematics, General, Ophthalmic Laboratory Technology/Technician, Pharmaceutical Sciences, Physics, General, Statistics, General�less",
                            financialneed = "No",
                            gender = "Any",
                            heritage = "N/A",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/28154/Faculty-of-Science-Undergraduate-Research-Scholarship",
                            name = "Faculty of Science Undergraduate Research Scholarship",
                            notes = "The Faculty of Science awards 16 of these scholarships to the best eligible students. This scholarship consists of two work terms with a research group at the Faculty of Science or the Faculty of Medicine (first work term = $5,000; second work term = $6,500). Students must be enrolled full time, for the first time in September, in an undergraduate program at the Faculty of Science and have a minimum admission average of 92%. They must also demonstrate research skills and involvement in extracurricular scientific activities. Applications must include a letter of recommendation from a science teacher and a 250-word text describing how the candidate explores their passion for science and shares it with others. Students must also be available for an interview in the spring. Applications must be submitted online.",
                            regionofresidence = "n/s",
                            regionofstudy = "n/s",
                            schoolofstudy = "University of Ottawa/Universit� d'Ottawa",
                            schoolsattended = "Any School",
                            yearofstudy = "Entering first year"
                        },
                        new
                        {
                            id = 8,
                            academicstanding = "N/A",
                            activities = "n/s",
                            amount = "$15,000",
                            citizenship = "Canada",
                            contactinfoaddress = "135 Michael Cowpland Drive Suite 105, Kanata, ON, Canada.  K2M 2E9",
                            contactinfoemail = "info@cnf-fiic.ca",
                            contactinfoname = "Canadian Nurses Foundation",
                            contactinfophone = "6136800879 x 221",
                            courseload = "Full-time or Part-time",
                            deadline = "March 15, 2024",
                            fieldofstudy = "Family Practice Nurse/Nurse Practitioner, Nursing Administration (MSN, MS, PhD), Nursing Science (MS, PhD), Nursing/Registered Nurse (RN, ASN, BSN, MSN)",
                            financialneed = "No",
                            gender = "N/A",
                            heritage = "N/A",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/64940/Dr.-Dorothy-J.-Kergin-Fellowship",
                            name = "Dr. Dorothy J. Kergin Fellowship",
                            notes = "Open to all eligible students at the master and doctorate level. Doctorate prize: $10,000; Master's prize: $5000.",
                            regionofresidence = "n/s",
                            regionofstudy = "Canada",
                            schoolofstudy = "Any School",
                            schoolsattended = "Any School",
                            yearofstudy = "All Years"
                        },
                        new
                        {
                            id = 9,
                            academicstanding = "N/A",
                            activities = "n/s",
                            amount = "$1,000",
                            citizenship = "Canada",
                            contactinfoaddress = "135 Michael Cowpland Drive Suite 105, Kanata, ON, Canada.  K2M 2E9",
                            contactinfoemail = "info@cnf-fiic.ca",
                            contactinfoname = "Canadian Nurses Foundation",
                            contactinfophone = "6136800879 x 221",
                            courseload = "Full-time or Part-time",
                            deadline = "March 15, 2024",
                            fieldofstudy = "Family Practice Nurse/Nurse Practitioner, Nursing Science (MS, PhD), Nursing/Registered Nurse (RN, ASN, BSN, MSN)",
                            financialneed = "No",
                            gender = "N/A",
                            heritage = "N/A",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/84076/Diversability/Disability-Award",
                            name = "Diversability/Disability Award",
                            notes = "Available to students who self-identify as having a diversability and/or disability and are currently enrolled in a RPN, LPN, or RN program. You must submit a 500-word essay detailing your experiences as a nursing student with a diversability and/or disability (positive or negative).",
                            regionofresidence = "n/s",
                            regionofstudy = "Canada",
                            schoolofstudy = "Any School",
                            schoolsattended = "Any School",
                            yearofstudy = "All Years"
                        },
                        new
                        {
                            id = 11,
                            academicstanding = "N/A",
                            activities = "School or Community Service",
                            amount = "$1,000",
                            citizenship = "Any",
                            contactinfoaddress = "700 Coronation Blvd, Cambridge, ON, Canada.  N1R 3G2",
                            contactinfoemail = "bcollins@cmh.org",
                            contactinfoname = "Bonnie Collins ",
                            contactinfophone = "N/A",
                            courseload = "Full-time or Part-time",
                            deadline = "July 17, 2024",
                            fieldofstudy = "Health Professions and Related Clinical Sciences, Other, Nursing, Other, Registered Nursing, Nursing Administration, Nursing Research and Clinical Nursing, Other",
                            financialneed = "Yes",
                            gender = "Any",
                            heritage = "Any Visible Minority",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/67251/CMH-Staff-Trust-Diversity-Bursary",
                            name = "CMH Staff Trust Diversity Bursary",
                            notes = "The CMH Staff Trust Fund is an employee led and funded trust. For almost 50 years it has donated to local charities and organizations that help those in need in Cambridge, North Dumfries and the Region of Waterloo. In addition to supporting local charities, the CMH Staff Trust Fund members have developed an education bursary to help increase diversity in health care.\n\nThe Cambridge Memorial Hospital (CMH) Staff Trust Diversity Bursary is to assist African Canadians, Indigenous people, persons of colour, persons with disabilities and/or those identifying as 2SLGBTQIA+ in their pursuit of post-secondary education in a health-related discipline. The longer term goal is to create a more diverse health care workforce.\n\nTo be considered, bursary applicants must:\n\nIdentify as an African Canadian, Indigenous person, person of colour, having a disability, and/or belonging to the 2SLGBTQIA+ community.\nBe a resident of the Region of Waterloo\nBe starting or continuing full or part-time studies for the academic year in a Canadian post-secondary institution that is recognized by the Universities Canada or Colleges and Institutes Canada.",
                            regionofresidence = "Ontario",
                            regionofstudy = "Canada",
                            schoolofstudy = "Any School",
                            schoolsattended = "Any School",
                            yearofstudy = "All Years"
                        },
                        new
                        {
                            id = 13,
                            academicstanding = "N/A",
                            activities = "n/s",
                            amount = "$7,500",
                            citizenship = "Canada",
                            contactinfoaddress = "135 Michael Cowpland Drive Suite 105, Kanata, ON, Canada.  K2M 2E9",
                            contactinfoemail = "info@cnf-fiic.ca",
                            contactinfoname = "Canadian Nurses Foundation",
                            contactinfophone = "6136800879 x 221",
                            courseload = "Full-time or Part-time",
                            deadline = "March 15, 2024",
                            fieldofstudy = "Family Practice Nurse/Nurse Practitioner, Nursing Science (MS, PhD), Nursing/Registered Nurse (RN, ASN, BSN, MSN)",
                            financialneed = "No",
                            gender = "N/A",
                            heritage = "N/A",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/84203/Frances-Moran-Award",
                            name = "Frances Moran Award",
                            notes = "Open to all nursing students in a Doctoral nursing program.",
                            regionofresidence = "n/s",
                            regionofstudy = "Canada",
                            schoolofstudy = "Any School",
                            schoolsattended = "Any School",
                            yearofstudy = "All Years"
                        },
                        new
                        {
                            id = 14,
                            academicstanding = "N/A",
                            activities = "n/s",
                            amount = "$15,000",
                            citizenship = "Canada",
                            contactinfoaddress = "135 Michael Cowpland Drive Suite 105, Kanata, ON, Canada.  K2M 2E9",
                            contactinfoemail = "info@cnf-fiic.ca",
                            contactinfoname = "Canadian Nurses Foundation",
                            contactinfophone = "6136800879 x 221",
                            courseload = "Full-time or Part-time",
                            deadline = "March 15, 2024",
                            fieldofstudy = "Family Practice Nurse/Nurse Practitioner, Nursing Administration (MSN, MS, PhD), Nursing Science (MS, PhD), Nursing/Registered Nurse (RN, ASN, BSN, MSN)",
                            financialneed = "No",
                            gender = "N/A",
                            heritage = "N/A",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/64940/Dr.-Dorothy-J.-Kergin-Fellowship",
                            name = "Dr. Dorothy J. Kergin Fellowship",
                            notes = "Open to all eligible students at the master and doctorate level. Doctorate prize: $10,000; Master's prize: $5000.",
                            regionofresidence = "n/s",
                            regionofstudy = "Canada",
                            schoolofstudy = "Any School",
                            schoolsattended = "Any School",
                            yearofstudy = "All Years"
                        },
                        new
                        {
                            id = 15,
                            academicstanding = "N/A",
                            activities = "n/s",
                            amount = "$1,500",
                            citizenship = "Any",
                            contactinfoaddress = "3333 University Way, Prince George, BC, Canada.  V2N 4Z9",
                            contactinfoemail = "awards@unbc.ca",
                            contactinfoname = "Awards and Financial Aid",
                            contactinfophone = "(250) 960-6319",
                            courseload = "Full-time",
                            deadline = "April 01, 2024",
                            fieldofstudy = "English Creative Writing, English Language and Literature, General, Journalism",
                            financialneed = "Yes",
                            gender = "Female",
                            heritage = "N/A",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/4070/Eileen-Williston-Bursary",
                            name = "Eileen Williston Bursary",
                            notes = "Open to a full-time student enrolled and majoring in the English program or other programs related to careers in creative writing or journalism. Preference given to mature women students. Minimum GPA of 2 required.",
                            regionofresidence = "International or Visa Student, Canada",
                            regionofstudy = "British Columbia",
                            schoolofstudy = "University of Northern British Columbia",
                            schoolsattended = "Any School",
                            yearofstudy = "All Years"
                        },
                        new
                        {
                            id = 18,
                            academicstanding = "N/A",
                            activities = "Volunteer",
                            amount = "$500",
                            citizenship = "Canada",
                            contactinfoaddress = "101 � 44981 Commercial Ct, Chilliwack, BC, Canada.  V2R 0E6",
                            contactinfoemail = "manufacturing@safetyalliancebc.ca",
                            contactinfoname = "Jennifer Wiebe",
                            contactinfophone = "16047959595",
                            courseload = "Full-time",
                            deadline = "March 15, 2024",
                            fieldofstudy = "Hazardous Materials Information Systems Technology/Technician, Industrial Safety Technology/Technician, Occupational Safety and Health Technology/Technician, Quality Control and Safety Technologies/Technicians, Other",
                            financialneed = "Yes",
                            gender = "N/A",
                            heritage = "N/A",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/66102/Julie-Cole-Bursary-for-Studies-in-Occupational-Health-and-Safety",
                            name = "Julie Cole Bursary for Studies in Occupational Health and Safety",
                            notes = "The loss of Julie Cole in 2020 left a hole in the safety community of British Columbia. An external auditor for the Manufacturing Safety Alliance of BC and health and safety manager, a principal consultant and safety trainer, and Manager of Health and Wellness for School District 20, Julie was a vital member of the safety community.\n\nThe Alliance has created a new bursary in her honour to support a student who shares Julie�s passion for Occupational Health and Safety.\n\n\nThis award will support a student pursuing a career in Occupational Health and Safety through post-secondary studies with demonstrated genuine financial need.\n\nThe Manufacturing Safety Alliance of BC is a leading provider of health and safety services in BC. An industry-funded organization with a board of directors elected from BC manufacturing industries, the Alliance is dedicated to ensuring Occupational Health and Safety professionals of the future are well qualified to provide industry advice and leadership.\n\n\n\nApplications will be accepted from students enrolling in a full-time, accredited Occupational Health and Safety program at college or university in BC (BCIT, UBC)\nApplications will be accepted from high school graduates and those furthering their education in health and safety graduate studies as outlined in the list of qualified programs\nApplicants will submit abstracts showing their academic results\nApplicants will submit an essay of 750 to 1,200 words explaining why workplace health and safety is important to them, and why they are pursuing this course of study\nApplicants will include information about their financial need in their application\nApplicants will be Canadian citizens or permanent residents residing in the province of B.C.",
                            regionofresidence = "British Columbia",
                            regionofstudy = "British Columbia",
                            schoolofstudy = "British Columbia Institute of Technology, Langara College, Simon Fraser University, Simon Fraser University - Faculty of Applied Sciences, The University of British Columbia - Vancouver, University of Northern British Columbia�more, University of Victoria�less",
                            schoolsattended = "Any School",
                            yearofstudy = "All Years"
                        },
                        new
                        {
                            id = 19,
                            academicstanding = "N/A",
                            activities = "n/s",
                            amount = "$4,000",
                            citizenship = "Any",
                            contactinfoaddress = "210 Administration-Humanities Building, Regina, SK, Canada.  S4S 0A2",
                            contactinfoemail = "Scholarships@uregina.ca",
                            contactinfoname = "Student Awards & Financial Aid",
                            contactinfophone = "(306) 585-5556",
                            courseload = "Full-time",
                            deadline = "March 15, 2024",
                            fieldofstudy = "Electrical, Electronics and Communications Engineering, Engineering, General, Environmental Engineering Technology/Environmental Technology, Industrial Engineering, Petroleum Engineering",
                            financialneed = "Yes",
                            gender = "N/A",
                            heritage = "Aboriginal,Indigenous",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/71367/Association-of-Professional-Engineers-&-Geoscientists-of-Saskatchewan-(APEGS)-Entrance-Bursary-(Engineering)",
                            name = "Association of Professional Engineers & Geoscientists of Saskatchewan (APEGS) Entrance Bursary (Engineering)",
                            notes = "1 bursary of $4,000.00 will be presented to an entering Engineering student and 1 bursary of $4,000.00 will be presented to an entering Engineering student with a preference to a student who is self-declared Indigenous.The bursary will be presented to the University of Regina entering student who meets the following criteria:\n\nEntering the Faculty of Engineering and Applied Science degree program in any Engineering discipline;\nRegistered and remains registered in a minimum of 9 credit hours in the semester the bursary is presented;\nDemonstrated financial need; and\nSelf-declared Indigenous student (for one of the entrance bursaries).\nNote: The student recipient must agree to have their contact information (phone number and email) shared with the Donor. The student recipient must be willing to be highlighted in the Donor's newsletter, website and other communications vehicles.",
                            regionofresidence = "n/s",
                            regionofstudy = "Saskatchewan",
                            schoolofstudy = "University of Regina",
                            schoolsattended = "Any School",
                            yearofstudy = "Entering first year"
                        },
                        new
                        {
                            id = 21,
                            academicstanding = "N/A",
                            activities = "n/s",
                            amount = "$10,000",
                            citizenship = "Canada",
                            contactinfoaddress = "2282 Bloor Street West, Toronto, ON, Canada.  M6S 1N9",
                            contactinfoemail = "info@bcufoundation.com",
                            contactinfoname = "BCU Foundation",
                            contactinfophone = "416-763-3388",
                            courseload = "Full-time",
                            deadline = "March 31, 2024",
                            fieldofstudy = "Accounting, Business Administration and Management, General, Business/Commerce, General, Computer Science, Engineering, General, Finance, General�more, Physical Sciences, Social Sciences, General�less",
                            financialneed = "No",
                            gender = "Any",
                            heritage = "Ukrainian",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/72782/Canada-150-Fund-Graduate-Student-Scholarship",
                            name = "Canada 150 Fund Graduate Student Scholarship",
                            notes = "BCU Foundation is committed to fostering the development of future generations of scholars and young professionals who will flourish in their careers, make meaningful and lasting contributions to the development of their Ukrainian Canadian community, and continue the tradition of excellence set by Ukrainians in Canada.\n\n\nIn 2017 BCU Foundation launched the Canada 150 Fund in commemoration of Canada's 150th anniversary of Confederation. The Fund provides an annual scholarship for Ukrainian Canadian graduate students and young scholars pursuing a graduate degree, including Master's, MBA, PhD, or post-doctoral research at a recognized North American institution.",
                            regionofresidence = "Canada",
                            regionofstudy = "Canada, United States",
                            schoolofstudy = "Any School",
                            schoolsattended = "Any School",
                            yearofstudy = "All Years"
                        },
                        new
                        {
                            id = 23,
                            academicstanding = "N/A",
                            activities = "n/s",
                            amount = "$4,000",
                            citizenship = "Any",
                            contactinfoaddress = "210 Administration-Humanities Building, Regina, SK, Canada.  S4S 0A2",
                            contactinfoemail = "Scholarships@uregina.ca",
                            contactinfoname = "Student Awards & Financial Aid",
                            contactinfophone = "(306) 585-5556",
                            courseload = "Full-time",
                            deadline = "March 15, 2024",
                            fieldofstudy = "Electrical, Electronics and Communications Engineering, Engineering, General, Environmental Engineering Technology/Environmental Technology, Industrial Engineering, Petroleum Engineering",
                            financialneed = "Yes",
                            gender = "N/A",
                            heritage = "Aboriginal,Indigenous",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/71367/Association-of-Professional-Engineers-&-Geoscientists-of-Saskatchewan-(APEGS)-Entrance-Bursary-(Engineering)",
                            name = "Association of Professional Engineers & Geoscientists of Saskatchewan (APEGS) Entrance Bursary (Engineering)",
                            notes = "1 bursary of $4,000.00 will be presented to an entering Engineering student and 1 bursary of $4,000.00 will be presented to an entering Engineering student with a preference to a student who is self-declared Indigenous.The bursary will be presented to the University of Regina entering student who meets the following criteria:\n\nEntering the Faculty of Engineering and Applied Science degree program in any Engineering discipline;\nRegistered and remains registered in a minimum of 9 credit hours in the semester the bursary is presented;\nDemonstrated financial need; and\nSelf-declared Indigenous student (for one of the entrance bursaries).\nNote: The student recipient must agree to have their contact information (phone number and email) shared with the Donor. The student recipient must be willing to be highlighted in the Donor's newsletter, website and other communications vehicles.",
                            regionofresidence = "n/s",
                            regionofstudy = "Saskatchewan",
                            schoolofstudy = "University of Regina",
                            schoolsattended = "Any School",
                            yearofstudy = "Entering first year"
                        },
                        new
                        {
                            id = 25,
                            academicstanding = "N/A",
                            activities = "n/s",
                            amount = "$10,000",
                            citizenship = "Canada",
                            contactinfoaddress = "135 Michael Cowpland Drive Suite 105, Kanata, ON, Canada.  K2M 2E9",
                            contactinfoemail = "info@cnf-fiic.ca",
                            contactinfoname = "Canadian Nurses Foundation",
                            contactinfophone = "6136800879 x 221",
                            courseload = "Full-time or Part-time",
                            deadline = "March 15, 2024",
                            fieldofstudy = "Family Practice Nurse/Nurse Practitioner, Nursing Science (MS, PhD), Nursing/Registered Nurse (RN, ASN, BSN, MSN)",
                            financialneed = "No",
                            gender = "N/A",
                            heritage = "N/A",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/64945/NANB/TD-Meloche-Monnex-Centennial-Doctoral-Scholarship",
                            name = "NANB/TD Meloche Monnex Centennial Doctoral Scholarship",
                            notes = "Registered nurses in New Brunswick studying at the doctoral level from all domains of practice. Available only to New Brunswick residents who are registered on the practicing register of NANB. An individual may receive the Scholarship one time only.",
                            regionofresidence = "New Brunswick",
                            regionofstudy = "Canada",
                            schoolofstudy = "Any School",
                            schoolsattended = "Any School",
                            yearofstudy = "All Years"
                        },
                        new
                        {
                            id = 26,
                            academicstanding = "N/A",
                            activities = "n/s",
                            amount = "$6,000",
                            citizenship = "Canada",
                            contactinfoaddress = "135 Michael Cowpland Drive Suite 105, Kanata, ON, Canada.  K2M 2E9",
                            contactinfoemail = "info@cnf-fiic.ca",
                            contactinfoname = "Canadian Nurses Foundation",
                            contactinfophone = "6136800879 x 221",
                            courseload = "Full-time or Part-time",
                            deadline = "March 15, 2024",
                            fieldofstudy = "Family Practice Nurse/Nurse Practitioner, Nursing Science (MS, PhD), Nursing/Registered Nurse (RN, ASN, BSN, MSN)",
                            financialneed = "No",
                            gender = "N/A",
                            heritage = "N/A",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/84204/Carolyn-Sifton-Research-Grant",
                            name = "Carolyn Sifton Research Grant",
                            notes = "Open to all nurses with a focus in at risk youth.",
                            regionofresidence = "n/s",
                            regionofstudy = "Canada",
                            schoolofstudy = "Any School",
                            schoolsattended = "Any School",
                            yearofstudy = "All Years"
                        },
                        new
                        {
                            id = 27,
                            academicstanding = "N/A",
                            activities = "n/s",
                            amount = "$4,000",
                            citizenship = "Any",
                            contactinfoaddress = "210 Administration-Humanities Building, Regina, SK, Canada.  S4S 0A2",
                            contactinfoemail = "Scholarships@uregina.ca",
                            contactinfoname = "Student Awards & Financial Aid",
                            contactinfophone = "(306) 585-5556",
                            courseload = "Full-time",
                            deadline = "March 15, 2024",
                            fieldofstudy = "Electrical, Electronics and Communications Engineering, Engineering, General, Environmental Engineering Technology/Environmental Technology, Industrial Engineering, Petroleum Engineering",
                            financialneed = "Yes",
                            gender = "N/A",
                            heritage = "Aboriginal,Indigenous",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/71367/Association-of-Professional-Engineers-&-Geoscientists-of-Saskatchewan-(APEGS)-Entrance-Bursary-(Engineering)",
                            name = "Association of Professional Engineers & Geoscientists of Saskatchewan (APEGS) Entrance Bursary (Engineering)",
                            notes = "1 bursary of $4,000.00 will be presented to an entering Engineering student and 1 bursary of $4,000.00 will be presented to an entering Engineering student with a preference to a student who is self-declared Indigenous.The bursary will be presented to the University of Regina entering student who meets the following criteria:\n\nEntering the Faculty of Engineering and Applied Science degree program in any Engineering discipline;\nRegistered and remains registered in a minimum of 9 credit hours in the semester the bursary is presented;\nDemonstrated financial need; and\nSelf-declared Indigenous student (for one of the entrance bursaries).\nNote: The student recipient must agree to have their contact information (phone number and email) shared with the Donor. The student recipient must be willing to be highlighted in the Donor's newsletter, website and other communications vehicles.",
                            regionofresidence = "n/s",
                            regionofstudy = "Saskatchewan",
                            schoolofstudy = "University of Regina",
                            schoolsattended = "Any School",
                            yearofstudy = "Entering first year"
                        },
                        new
                        {
                            id = 28,
                            academicstanding = "N/A",
                            activities = "n/s",
                            amount = "$9,000",
                            citizenship = "Canada",
                            contactinfoaddress = "135 Michael Cowpland Drive Suite 105, Kanata, ON, Canada.  K2M 2E9",
                            contactinfoemail = "info@cnf-fiic.ca",
                            contactinfoname = "Canadian Nurses Foundation",
                            contactinfophone = "6136800879 x 221",
                            courseload = "Full-time or Part-time",
                            deadline = "March 15, 2024",
                            fieldofstudy = "Family Practice Nurse/Nurse Practitioner, Nursing Science (MS, PhD), Nursing/Registered Nurse (RN, ASN, BSN, MSN)",
                            financialneed = "No",
                            gender = "N/A",
                            heritage = "Aboriginal,First Nation,Indigenous",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/64948/TD-Insurance-Indigenous-Nursing-Award",
                            name = "TD Insurance Indigenous Nursing Award",
                            notes = "Open to all eligible Indigenous nurses studying at the doctoral level.",
                            regionofresidence = "n/s",
                            regionofstudy = "Canada",
                            schoolofstudy = "Any School",
                            schoolsattended = "Any School",
                            yearofstudy = "All Years"
                        },
                        new
                        {
                            id = 29,
                            academicstanding = "N/A",
                            activities = "n/s",
                            amount = "$10,000",
                            citizenship = "Canada",
                            contactinfoaddress = "135 Michael Cowpland Drive Suite 105, Kanata, ON, Canada.  K2M 2E9",
                            contactinfoemail = "info@cnf-fiic.ca",
                            contactinfoname = "Canadian Nurses Foundation",
                            contactinfophone = "6136800879 x 221",
                            courseload = "Full-time or Part-time",
                            deadline = "March 15, 2024",
                            fieldofstudy = "Family Practice Nurse/Nurse Practitioner, Nursing Science (MS, PhD), Nursing/Registered Nurse (RN, ASN, BSN, MSN)",
                            financialneed = "No",
                            gender = "N/A",
                            heritage = "N/A",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/64945/NANB/TD-Meloche-Monnex-Centennial-Doctoral-Scholarship",
                            name = "NANB/TD Meloche Monnex Centennial Doctoral Scholarship",
                            notes = "Registered nurses in New Brunswick studying at the doctoral level from all domains of practice. Available only to New Brunswick residents who are registered on the practicing register of NANB. An individual may receive the Scholarship one time only.",
                            regionofresidence = "New Brunswick",
                            regionofstudy = "Canada",
                            schoolofstudy = "Any School",
                            schoolsattended = "Any School",
                            yearofstudy = "All Years"
                        },
                        new
                        {
                            id = 30,
                            academicstanding = "N/A",
                            activities = "n/s",
                            amount = "$6,000",
                            citizenship = "Canada",
                            contactinfoaddress = "135 Michael Cowpland Drive Suite 105, Kanata, ON, Canada.  K2M 2E9",
                            contactinfoemail = "info@cnf-fiic.ca",
                            contactinfoname = "Canadian Nurses Foundation",
                            contactinfophone = "6136800879 x 221",
                            courseload = "Full-time or Part-time",
                            deadline = "March 15, 2024",
                            fieldofstudy = "Family Practice Nurse/Nurse Practitioner, Nursing Science (MS, PhD), Nursing/Registered Nurse (RN, ASN, BSN, MSN)",
                            financialneed = "No",
                            gender = "N/A",
                            heritage = "N/A",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/84204/Carolyn-Sifton-Research-Grant",
                            name = "Carolyn Sifton Research Grant",
                            notes = "Open to all nurses with a focus in at risk youth.",
                            regionofresidence = "n/s",
                            regionofstudy = "Canada",
                            schoolofstudy = "Any School",
                            schoolsattended = "Any School",
                            yearofstudy = "All Years"
                        },
                        new
                        {
                            id = 31,
                            academicstanding = "N/A",
                            activities = "n/s",
                            amount = "$7,500",
                            citizenship = "Canada",
                            contactinfoaddress = "135 Michael Cowpland Drive Suite 105, Kanata, ON, Canada.  K2M 2E9",
                            contactinfoemail = "info@cnf-fiic.ca",
                            contactinfoname = "Canadian Nurses Foundation",
                            contactinfophone = "6136800879 x 221",
                            courseload = "Full-time or Part-time",
                            deadline = "March 15, 2024",
                            fieldofstudy = "Family Practice Nurse/Nurse Practitioner, Nursing Science (MS, PhD), Nursing/Registered Nurse (RN, ASN, BSN, MSN)",
                            financialneed = "No",
                            gender = "N/A",
                            heritage = "N/A",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/84203/Frances-Moran-Award",
                            name = "Frances Moran Award",
                            notes = "Open to all nursing students in a Doctoral nursing program.",
                            regionofresidence = "n/s",
                            regionofstudy = "Canada",
                            schoolofstudy = "Any School",
                            schoolsattended = "Any School",
                            yearofstudy = "All Years"
                        },
                        new
                        {
                            id = 32,
                            academicstanding = "N/A",
                            activities = "n/s",
                            amount = "$15,000",
                            citizenship = "Canada",
                            contactinfoaddress = "135 Michael Cowpland Drive Suite 105, Kanata, ON, Canada.  K2M 2E9",
                            contactinfoemail = "info@cnf-fiic.ca",
                            contactinfoname = "Canadian Nurses Foundation",
                            contactinfophone = "6136800879 x 221",
                            courseload = "Full-time or Part-time",
                            deadline = "March 15, 2024",
                            fieldofstudy = "Family Practice Nurse/Nurse Practitioner, Nursing Administration (MSN, MS, PhD), Nursing Science (MS, PhD), Nursing/Registered Nurse (RN, ASN, BSN, MSN)",
                            financialneed = "No",
                            gender = "N/A",
                            heritage = "N/A",
                            levelofstudy = "No",
                            link = "https://www.scholarshipscanada.com//Scholarships/64940/Dr.-Dorothy-J.-Kergin-Fellowship",
                            name = "Dr. Dorothy J. Kergin Fellowship",
                            notes = "Open to all eligible students at the master and doctorate level. Doctorate prize: $10,000; Master's prize: $5000.",
                            regionofresidence = "n/s",
                            regionofstudy = "Canada",
                            schoolofstudy = "Any School",
                            schoolsattended = "Any School",
                            yearofstudy = "All Years"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
